version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-freecad_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/freecad:1.1.4@sha256:8ada0e7264ef5df812f14162cbe45f109bc0e3e0d4e0b579825f05bf08718e1f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/freecad/config
        target: /config
