version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-freecad_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/freecad:1.1.3@sha256:6989685024064a090e6d11e2663a95cff502eb743676dfcf21d950e196201a9d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/freecad/config
        target: /config
