version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cops_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/cops:4.5.4@sha256:c94974699131e87de2815e577d91c1677e3fd5a78b2316c658133d313326651d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/cops/config
        target: /config
      - type: bind
        source: /DATA/AppData/cops/books
        target: /books
