version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-yaak_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/yaak:2026.8.0@sha256:89af05e2a1558004a76e48d62377c021cb67acc7520950976d6b367ace8c411f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
