version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-yaak_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/yaak:2026.8.1@sha256:552e20ac2a89c871b0ea5e48cdda6c5f8961b07f2f1d6947b786df084ea0ce14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
