version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-yaak_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/yaak:2026.8.1@sha256:03ee7b148139da77eaa2c2d29db2d15025c2f8e62331d7c2d8f02df1838a9381
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
