version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-hrconvert2_app_1
      APP_PORT: ' 80'
  app:
    image: dwaaan/hrconvert2-docker:latest
    restart: unless-stopped
