version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-librewolf_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/librewolf:157.0.1@sha256:91c034c43f4e00b92fa39c0d0cc470ba9554bb8ffd5db4008881b4e700241a64
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LIBREWOLF_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/librewolf/config
        target: /config
