version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-librewolf_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/librewolf:156.0.1@sha256:6adfdef0802c4ccbe9c36c4c2c3df234d6824cd8e6a9600edb23f845236ac296
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LIBREWOLF_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/librewolf/config
        target: /config
