version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wikijs_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/wikijs:2.5.315@sha256:1cbb7cd39f62b12025b6cb5fea4f95629833162c72bf0604c568090f343c8665
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_TYPE: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    volumes:
      - type: bind
        source: /DATA/AppData/wikijs/config
        target: /config
      - type: bind
        source: /DATA/AppData/wikijs/data
        target: /data
