version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscodium-web_app_1
      APP_PORT: ' 8000'
  app:
    image: linuxserver/vscodium-web:1.135.06055@sha256:c1bc670d4f9bf10994090715923d0e62ff339749c19028c2d483759568e139e6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONNECTION_TOKEN: ''
      CONNECTION_TOKEN_FILE: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      CODE_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium-web/config
        target: /config
