version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-duckstation_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/duckstation:version-latest@sha256:b272b36098bd40328e2496a616f49e47360ee5550e46aa2ffd7cbc8d232d5c50
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/duckstation/config
        target: /config
