version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-duckstation_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/duckstation:version-latest@sha256:764fe1e10a888ee70bfa36cead6a4c4088479b99d57ab7fc7a246c4a74ef0bfa
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/duckstation/config
        target: /config
