version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-d2-builder_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/d2-builder:0.9.0@sha256:728e6ecb5270a091d768707608826735285a16ba2c4b9ce121ac2239f8fa31a0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/d2-builder/config
        target: /config
