version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-rsnapshot_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/rsnapshot:1.4.5@sha256:40b42ceaf1ca02e4a598de0ee6b862dca3d4c8bb85aaad969b21529f034542e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
