version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-handbrake_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/handbrake:1.11.2@sha256:3529715c666cc7775ae7642eb07baeca9acbbe285bb35d0bcebbbbc18ce17263
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
