version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-handbrake_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/handbrake:1.11.2@sha256:fdd6ce95ac014efbd64920af2428fae49343f6332ea75e28316eb2b7a69f8069
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
