version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-handbrake_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/handbrake:1.11.2@sha256:283d18aa7029adec4ede8c7df160300a3cbf942560d8122aae2e2f35d92e0826
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
