version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-changedetection-io_app_1
      APP_PORT: ' 5000'
  app:
    image: linuxserver/changedetection.io:0.60.8@sha256:91a1670814112dfe910bd2dbf33fc92b856978e077024fd378923b0bf5b29343
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
      PLAYWRIGHT_DRIVER_URL: ''
    volumes:
      - type: bind
        source: /DATA/AppData/changedetection.io/config
        target: /config
