version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-changedetection-io_app_1
      APP_PORT: ' 5000'
  app:
    image: linuxserver/changedetection.io:0.60.7@sha256:5a8cd61666feac9f91292e1f7a9dfa37f6e35674367b2e20252f9a126e2c8994
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
      PLAYWRIGHT_DRIVER_URL: ''
    volumes:
      - type: bind
        source: /DATA/AppData/changedetection.io/config
        target: /config
