version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-libreoffice_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/libreoffice:25.8.7@sha256:75295ed8efc36ab808714787d4e2062621d016295f19d3f7a953d8fef016c24f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
