version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-libreoffice_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/libreoffice:25.8.7@sha256:68f6fcab0306359cd6c6c641da415b3dd695470078908875d47573c88c517390
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
