version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscode_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vscode:1.138.0@sha256:126a944773cdfc8d43a4a7e7438a89df817bfe426ac1981d1d5ccb963ca7ac47
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/vscode/config
        target: /config
