version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscode_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vscode:1.139.1@sha256:36d514ed8b2ef676d8dbfbb90e523e121832ba791913ab02d9554151de3aa83d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/vscode/config
        target: /config
