version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscode_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vscode:1.140.0@sha256:008276f42f301068df07ee08a9a271dc33c3cdddef50398c660e06859de2a55c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/vscode/config
        target: /config
