version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-drawio_app_1
      APP_PORT: "8080"
  app:
    image: jgraph/drawio:32.0.2@sha256:01a60ec393578bd20194b4da6272fd0b2ae679c57f2027ad478100d96d81965b
    restart: unless-stopped
