version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-drawio_app_1
      APP_PORT: "8080"
  app:
    image: jgraph/drawio:31.4.6@sha256:139b43305b77c46575d5af5dcc7b6c38dc7ea22f430fdfe954fb8f96926643e5
    restart: unless-stopped
