version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-drawio_app_1
      APP_PORT: "8080"
  app:
    image: jgraph/drawio:32.2.0@sha256:eeb90e46cab38daf2b9f7887c9418d9fad219532cb03ad50826ef5a1f68d8a8e
    restart: unless-stopped
