version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-audacity_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/audacity:4.0.1@sha256:f58f99d173d53e0f407ac8588b8d7dec13a8ac55ec345be1ae1d7013c16ad4cb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
