version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-audacity_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/audacity:4.0.0@sha256:a919c462589ec4cec743c23adb3e4c73f591e81d91566388a0c0d1bbf0011dfd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
