version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-audacity_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/audacity:4.0.1@sha256:6e0761fff5269228c515e754e6d2bef8be353f939cf2a2eca3d30af7b4a6ee0f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
