version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-modrinth_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/modrinth:0.21.4@sha256:74cb8da4da2dbcdc1f0a9d12b30d53426213e89fa4b0824fe122e6d12dcfae84
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/modrinth/config
        target: /config
