version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vivaldi_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:43cc10f0b35f1a442aeb74035ea9137f2fa6655c9aba93ef9c3d803a6109ed0f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
