version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vivaldi_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:b5c17af7f4b5f9475302d9144b532ee5cbb57773a74bc307323c17f83cd0cd7c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
