version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-xemu_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/xemu:0.8.134@sha256:58479147a958912ed943857edf95f54e7b57f4cedff6b2863b30349ce36bcd85
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
