version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-xemu_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/xemu:0.8.134@sha256:eb5da0c57b28a9dddcc93e6cb6c7399c3c179d6943582d68926512abfaa1e14e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
