version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-xemu_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/xemu:0.8.134@sha256:ce23bd30c9fe166b3a167b87d6bcb88ee9b29740769ad9fd1ca2182ddb5544cf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
