version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webgrabplus_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/webgrabplus:5.6.1@sha256:8d5dd403b0f16d4a96ff19a8360ee75193f9429c95bd343c7a2922075fefc056
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webgrabplus/config
        target: /config
      - type: bind
        source: /DATA/AppData/webgrabplus/data
        target: /data
