version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webgrabplus_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/webgrabplus:5.6.1@sha256:f7db50b6169fbf2064bc64f8112dcf0454c3820818c5f809dab6359da13e6f34
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webgrabplus/config
        target: /config
      - type: bind
        source: /DATA/AppData/webgrabplus/data
        target: /data
