version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vlc_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vlc:3.0.23@sha256:f7fa5bbd34c9283c96224c3571ce1cf4c4f2a7d9b98df531af2158fd2311f1bd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VLC_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/vlc/config
        target: /config
