# Configuration for lancache setup
# Name of the big-bear-lancache application
version: "3.7"
# Service definitions for the big-bear-lancache application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-lancache_app_1
      APP_PORT: "80"
  # Service name: app
  app:
    image: lancachenet/monolithic:latest@sha256:37f28b362c939a333f3e4f12aa8ca80604cf75050b2f190d0ad972b2fedce00e # Docker image for the caching service
    environment:
      # Toggle for load balancer usage or separate IPs for each service
      - USE_GENERIC_CACHE=true
      # IPs for lancache monolithic instance; affects DNS resolution
      - LANCACHE_IP=10.0.39.1
      # Host IP for the DNS server binding
      - DNS_BIND_IP=10.0.39.1
      # Upstream DNS for forwarded lookups
      - UPSTREAM_DNS=8.8.8.8
      # Local storage path for cache data
      - CACHE_ROOT=./lancache
      # Customizable disk cache size
      - CACHE_DISK_SIZE=2000g
      # Memory allocation for nginx cache indexing
      - CACHE_INDEX_SIZE=500m
      # Maximum age for cached content
      - CACHE_MAX_AGE=3650d
      # Container timezone setting for log timestamps
      - TZ=UTC
    restart: unless-stopped
    volumes:
      # Mount points for cache and logs
      - ${APP_DATA_DIR}/cache:/data/cache
      - ${APP_DATA_DIR}/logs:/data/logs
  # DNS service configuration
  dns:
    image: lancachenet/lancache-dns:latest@sha256:cec61382a3b4b8ef6dfc4ff44eefd4028ea48662ff5930097bb366b69e22296c # Docker image for DNS service
    environment:
      # Toggle for load balancer usage or separate IPs for each service
      - USE_GENERIC_CACHE=true
      # IPs for lancache monolithic instance; affects DNS resolution
      - LANCACHE_IP=10.0.39.1
      # Host IP for the DNS server binding
      - DNS_BIND_IP=10.0.39.1
      # Upstream DNS for forwarded lookups
      - UPSTREAM_DNS=8.8.8.8
      # Local storage path for cache data
      - CACHE_ROOT=./lancache
      # Customizable disk cache size
      - CACHE_DISK_SIZE=2000g
      # Memory allocation for nginx cache indexing
      - CACHE_INDEX_SIZE=500m
      # Maximum age for cached content
      - CACHE_MAX_AGE=3650d
      # Container timezone setting for log timestamps
      - TZ=UTC
    restart: unless-stopped
