version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ungoogled-chromium_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/ungoogled-chromium:154.0.8037@sha256:59857b293c496b54f53918e3a00125fcbc523f3b16942dc8b7eea5954dc57b63
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
