version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-bambustudio_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/bambustudio:02.08.03@sha256:f6b7d67685a933d799e97872f72366a9250de068a73e2cc81d1d130f5e5ae348
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DARK_MODE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/bambustudio/config
        target: /config
