version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-duplicati_app_1
      APP_PORT: ' 8200'
  app:
    image: linuxserver/duplicati:2.4.0@sha256:78883c4ea7a33fd360c8cefe684609deed4ca12cf000ae7612f2f89bbfcb7369
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/AppData/duplicati/backups
        target: /backups
      - type: bind
        source: /DATA/AppData/duplicati/source
        target: /source
