version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-navidrome_app_1
      APP_PORT: "4533"
  app:
    image: deluan/navidrome:0.64.2@sha256:38dc2727bfcfd5ede290f8ada114fc90368146f265ae4701ddddbcbe2a44ee52
    volumes:
      - ./data:/data
      - ${APP_DATA_DIR}/music:/music:ro
    restart: unless-stopped
