version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-navidrome_app_1
      APP_PORT: "4533"
  app:
    image: deluan/navidrome:0.64.0@sha256:a384948b81bd1529986c5960169e7fc4fa00f46bde6bd517971a4c36671db2af
    volumes:
      - ./data:/data
      - ${APP_DATA_DIR}/music:/music:ro
    restart: unless-stopped
