version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pidgin_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pidgin:2.14.14@sha256:12c0f4103b37b53b4e84e3c5b7cea10992ff16e6f103c652d8eedfae11ba15a4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
