version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pidgin_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pidgin:2.14.14@sha256:bc65e4095567bbfc9f4ca224cf4123065f7ba651a94d17602d9263bd5221dc76
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
