version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-rustdesk_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/rustdesk:1.5.0@sha256:bb4c5161f1df20602c791a025c69a6dbb88231e4b3e33801f1771f04a6d06487
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/rustdesk/config
        target: /config
