version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-rustdesk_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/rustdesk:1.4.9@sha256:4e4d01107dcb3256ddf34b68f4f946171fa154352b433b454f77b95815d97216
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/rustdesk/config
        target: /config
