version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mastodon_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/mastodon:4.7.2@sha256:1a6db728094ad3940da36690d8f4ee2c41124fae653fdda3758e33776d7af41a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LOCAL_DOMAIN: $LOCAL_DOMAIN
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      ES_ENABLED: $ES_ENABLED
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: $ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: $ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: $ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      OTP_SECRET: $OTP_SECRET
      VAPID_PRIVATE_KEY: $VAPID_PRIVATE_KEY
      VAPID_PUBLIC_KEY: $VAPID_PUBLIC_KEY
      SMTP_SERVER: $SMTP_SERVER
      SMTP_PORT: $SMTP_PORT
      SMTP_LOGIN: $SMTP_LOGIN
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_FROM_ADDRESS: $SMTP_FROM_ADDRESS
      S3_ENABLED: $S3_ENABLED
      WEB_DOMAIN: $WEB_DOMAIN
      ES_HOST: $ES_HOST
      ES_PORT: $ES_PORT
      ES_USER: $ES_USER
      ES_PASS: $ES_PASS
      S3_BUCKET: $S3_BUCKET
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      S3_ALIAS_HOST: $S3_ALIAS_HOST
      SIDEKIQ_ONLY: $SIDEKIQ_ONLY
      SIDEKIQ_QUEUE: $SIDEKIQ_QUEUE
      SIDEKIQ_DEFAULT: $SIDEKIQ_DEFAULT
      SIDEKIQ_THREADS: $SIDEKIQ_THREADS
      DB_POOL: $DB_POOL
      NO_CHOWN: $NO_CHOWN
      MASTODON_PROMETHEUS_EXPORTER_ENABLED: $MASTODON_PROMETHEUS_EXPORTER_ENABLED
    volumes:
      - type: bind
        source: /DATA/AppData/mastodon/config
        target: /config
