version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wps-office_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/wps-office:11.1.0@sha256:f2f3aac75806992d893e24d9e438a04317954641cafdb744fd737bae9d80819f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/wps-office/config
        target: /config
