version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wps-office_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/wps-office:11.1.0@sha256:60bed84aaf47ba56057b89e3069f3721f8cec9f8e5905ed839cbaf879ad35c54
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/wps-office/config
        target: /config
