version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-syslog-ng_app_1
      APP_PORT: ' 514'
  app:
    image: linuxserver/syslog-ng:4.11.0@sha256:3ad97ed09bcacddf09520a566c06437dd42951604fe0197aeae7f2e4330ac93d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      LOG_TO_STDOUT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/syslog-ng/config
        target: /config
      - type: bind
        source: /var/log
        target: /var/log
