version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-openshot_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/openshot:4.0.0@sha256:01737ed98a46cb4fc93d4474b9f91e3cf00c4c60b0cc2017becdc1d51a7ac237
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/openshot/config
        target: /config
