version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-openshot_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/openshot:4.0.1@sha256:b26dec3801aec4350babeb7ae44496ceebcc3060aae1c32bbd96919a99946ee9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/openshot/config
        target: /config
