version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-hedgedoc_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/hedgedoc:1.12.0@sha256:8f0e4c57941a9cff0387d5b3c9f1f40facce1e948ca28261e42c5251eca21a19
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      CMD_DOMAIN: $CMD_DOMAIN
      CMD_URL_ADDPORT: $CMD_URL_ADDPORT
      CMD_PROTOCOL_USESSL: $CMD_PROTOCOL_USESSL
      CMD_PORT: $CMD_PORT
      CMD_ALLOW_ORIGIN: $CMD_ALLOW_ORIGIN
      CMD_DB_DIALECT: $CMD_DB_DIALECT
    volumes:
      - type: bind
        source: /DATA/AppData/hedgedoc/config
        target: /config
