version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-netboot-xyz_app_1
      APP_PORT: "3000"
  app:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz24@sha256:7bd0964fd3648cd3323772ad6ad8b0a507afe797385e4c0f587a8c23972ee4e3
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/assets:/assets
    environment:
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
      - TZ=UTC
    restart: unless-stopped
