version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webstation_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webstation:0.14.2-romm@sha256:3a6ddb89de3dae9865e9f3484b3e1dc0462d8d531007b5d4e93e423a368b6a89
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
