version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webstation_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webstation:0.14.0-romm@sha256:bc8d534ab9fa512f33cf3b86d65b64df3e5126db5963f41c0a5fa97a2654e6db
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
