version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webstation_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webstation:0.14.2-romm@sha256:13d7c0fb09ff936e7f22120368d711e19012f869ba33fd73ceda65f13db44715
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
