version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mediaelch_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mediaelch:2.12.0@sha256:aa208fee2929652751febabc2bfcd651b6d7dbec77a5adde66d06d86a5efe082
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mediaelch/config
        target: /config
