version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-qdirstat_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/qdirstat:2.0.20260928@sha256:6551ad061d5821c9c69147b230c45016ee453dccad15c69a3ad608da1ea33c67
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/qdirstat/config
        target: /config
      - type: bind
        source: /DATA/AppData/qdirstat/data
        target: /data
