version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webtop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webtop:arch-kde-version-2025-07-12@sha256:e38f6e952db39f1b498f22b74d7c4ed9241b95b6cc3c8baf55140d4ad9823f6a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
