version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webtop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webtop:arch-kde-version-2025-07-12@sha256:d55dd7f34fe70e9e39fb004e3f7ef5eb0fd74b24a771ba972a25a24ce24f65a6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
