version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webtop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webtop:arch-kde-version-2025-07-12@sha256:ed197a60c161b5d45a0d0137a5c47ecd136964c57791bf3151d01ad41ac6b988
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webtop/config
        target: /config
