version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-calibre-web_app_1
      APP_PORT: ' 8083'
  app:
    image: linuxserver/calibre-web:0.6.27@sha256:80b2a77b5925441c76607619fd406694570a50a0e32c229198dbb39e72da6fed
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: ''
      OAUTHLIB_RELAX_TOKEN_SCOPE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/calibre-web/config
        target: /config
      - type: bind
        source: /DATA/AppData/calibre-web/books
        target: /books
