version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-shotcut_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/shotcut:26.9.27@sha256:7cbfc1a31a0b6a302978bf4b8c5c55f602ac4ec130caa4b82479ccdf59517d14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/shotcut/config
        target: /config
