version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-eden_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/eden:0.2.1@sha256:91f5be6bb28b220661c194f7858559f47e3f412e4501d6b3e2814b803b0dee70
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/eden/config
        target: /config
