version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-xvfb_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/xvfb:debiantrixie-version-9d327c0f@sha256:db8c513160544109a1ed06256ea0fbdc8e40fc1f78e6096755f9c30bae8aa38a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /srv/lsio/xvfb/config
        target: /config
