version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-nova-dso-tracker_nova_1
      APP_PORT: "5001"
  nova:
    image: mrantonsg/nova-dso-tracker:6.2.0@sha256:eb5cd12f4c7627ec6e70051f4bccc5852db1efcd349402929b0c2cc0da2f1938
    volumes:
      - ${APP_DATA_DIR}/instance:/app/instance
    restart: unless-stopped
