version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-nova-dso-tracker_nova_1
      APP_PORT: "5001"
  nova:
    image: mrantonsg/nova-dso-tracker:6.2.2@sha256:1412e856855bce10147154ba207c11b904d3de50dbbfbb6a5fe0378a329620f0
    volumes:
      - ${APP_DATA_DIR}/instance:/app/instance
    restart: unless-stopped
