version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-nova-dso-tracker_nova_1
      APP_PORT: "5001"
  nova:
    image: mrantonsg/nova-dso-tracker:6.7.1@sha256:33b20216f6050c4dfbf6b933dc98e0c95f86c60b529189d394c8ef312da22052
    volumes:
      - ${APP_DATA_DIR}/instance:/app/instance
    restart: unless-stopped
