version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-nightlio_big-bear-nightlio-frontend_1
      APP_PORT: "5173"
  big-bear-nightlio-api:
    image: ghcr.io/shirsakm/nightlio-api:0.1.7@sha256:4f9b88a3eba36b67457052d08b0a71bb3210b72276da0b6432235ce5372e3cb4
    restart: unless-stopped
    environment:
      - SECRET_KEY=changeme
      - JWT_SECRET=changeme-too
      - CORS_ORIGINS=http://localhost:5173
      - ENABLE_GOOGLE_OAUTH=0
      - ENABLE_MOOD_MUSIC=0
      - DEFAULT_SELF_HOST_ID=selfhost_default_user
      - DATABASE_PATH=/app/data/nightlio.db
      - PORT=5000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - big_bear_nightlio_network
  big-bear-nightlio-frontend:
    image: ghcr.io/shirsakm/nightlio-frontend:0.1.7@sha256:0a2bd8ec3eefe6adfa79f4809bc57c9ef2d3094dcece13f7d3c5309bacfcc117
    restart: unless-stopped
    environment:
      - API_URL=http://big-bear-nightlio-api:5000
    depends_on:
      - big-bear-nightlio-api
    networks:
      - big_bear_nightlio_network
      - default
networks:
  big_bear_nightlio_network:
    driver: bridge
