version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cura_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/cura:5.13.0@sha256:2b7a8665a662478c0e486b3841a5eb7517c92c1c661b0d306de238f38ef64da9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
