version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cura_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/cura:5.13.0@sha256:1b111783e5bd9e7cc495a9a1f942f73f525730b2f8c59d72b9181bca7d1c3074
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
