version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cura_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/cura:5.13.0@sha256:fd98df9f9ac514f63e900dafb38d165b22d3c2918d61e72bb9526f9d676c59d7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
