version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-keepassxc_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/keepassxc:2.7.12@sha256:accf6914aa95ba027f197e0ab4d4c8e177728b9e5ad16a912febe7a6dd46c2f8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/keepassxc/config
        target: /config
