version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blade-of-agony_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blade-of-agony:3.1.20260924@sha256:72eedff1839fe51fd0a237dcefe292fab56ec91143069cbae68bbf8f10b5f0ea
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blade-of-agony/config
        target: /config
