version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blade-of-agony_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blade-of-agony:3.1.20261001@sha256:72d61ee18b609935c632df57cfbd420b62cc7ffc93c4ef4d83c81c841a0e5ebd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blade-of-agony/config
        target: /config
