version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blade-of-agony_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blade-of-agony:3.1.20260917@sha256:8926be7bc8b47c278a1436c5aaef79170be601adb8854d5e5156ea6de0607984
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blade-of-agony/config
        target: /config
