version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-inkscape_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/inkscape:1.4.2@sha256:31db35960100e924a3f6bd836c7b49e1dd8bc63858acef1618455fda4e6c337e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/inkscape/config
        target: /config
