version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-inkscape_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/inkscape:1.4.2@sha256:a7d4088f251e59123595acf94d0c5502ff17fc76ee38790b7b5335bf1377d52c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/inkscape/config
        target: /config
