version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-podfetch_app_1
      APP_PORT: "8000"
  app:
    image: samuel19982/podfetch:v5.2.2@sha256:6c145cc5427d7fb042016a7e4d42d2218acfc84f809b6a25680866cb97b8e852
    volumes:
      - ${APP_DATA_DIR}/podfetch/podcasts:/app/podcasts
      - ${APP_DATA_DIR}/podfetch/db:/app/db
    environment:
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - POLLING_INTERVAL=300
      - BASIC_AUTH=false
      - USERNAME=bigbear
      - PASSWORD=15c40698-3cd9-40ce-8039-e8d80fc1a030
      - GPODDER_INTEGRATION_ENABLED=false
    restart: unless-stopped
    networks:
      - podfetch-network
networks:
  podfetch-network:
    driver: bridge
