version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-rawtherapee_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/rawtherapee:5.13.20260927@sha256:3cbe79409125024131a8875d7ab1bb63810daa9b294cd7fbb1511a70b3aade8e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/rawtherapee/config
        target: /config
