version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wireguard_app_1
      APP_PORT: ' 51820'
  app:
    image: linuxserver/wireguard:1.0.20260223@sha256:216ca1ce9da7bfe26fb752111d952487804bd18933bbd4794970d424bf8adfe9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SERVERURL: ''
      SERVERPORT: ''
      PEERS: ''
      PEERDNS: ''
      INTERNAL_SUBNET: ''
      ALLOWEDIPS: ''
      PERSISTENTKEEPALIVE_PEERS: ''
      LOG_CONFS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/wireguard/config
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
