version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wireguard_app_1
      APP_PORT: ' 51820'
  app:
    image: linuxserver/wireguard:1.0.20260223@sha256:33c5e4260f5ddf9376fcb6f1ff90c0ccc3c63d2ab469595e33d178ecf8a4c4c6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SERVERURL: ''
      SERVERPORT: ''
      PEERS: ''
      PEERDNS: ''
      INTERNAL_SUBNET: ''
      ALLOWEDIPS: ''
      PERSISTENTKEEPALIVE_PEERS: ''
      LOG_CONFS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/wireguard/config
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
