version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-synclounge_app_1
      APP_PORT: ' 8088'
  app:
    image: linuxserver/synclounge:5.2.35@sha256:4bfe71ceebad2de95736a5588e12dbd96af050405b77f952bded5d805fe0765c
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
