version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-synclounge_app_1
      APP_PORT: ' 8088'
  app:
    image: linuxserver/synclounge:5.2.35@sha256:0d21be07263d4b0187a290649d949ecb899bc8fa9994b3d1648546ca7e054ce7
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
