version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-synclounge_app_1
      APP_PORT: ' 8088'
  app:
    image: linuxserver/synclounge:5.2.35@sha256:aae78ae2936b214d6733d56cbf3dd42fd9c79bcdf4655c00403b704dff9a9a69
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
