version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-luanti_app_1
      APP_PORT: ' 30000'
  app:
    image: linuxserver/luanti:5.17.0@sha256:5e605da9a3cc87dbcfb37a8803d8ab6b706b7798d896c1d8af509ecdeb4908ea
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CLI_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/luanti/config/.minetest
        target: /config/.minetest
