version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pydio-cells_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/pydio-cells:5.0.3@sha256:d549b020fbd759170d39580a66e31d807b06d0e3f885206ee1ee1ec546a426ce
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
