version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pydio-cells_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/pydio-cells:5.1.0@sha256:f3142b40fec79996f065ffb5d9ab25bc293dc18d88c0e75658465e23dcabbcce
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
