version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pydio-cells_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/pydio-cells:5.1.0@sha256:fa339560b49539a9ca4872b94805444d0a66bd8755af4cb6978ea94f73652657
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
