version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-jlesage-handbrake_big-bear-jlesage-handbrake_1
      APP_PORT: "5800"
  big-bear-jlesage-handbrake:
    image: jlesage/handbrake:v26.07.2@sha256:192f02fbdd651e54f7df918d2dca15ba9cc6851b01c7e534809a0277c8cacd84 # Docker image for the Handbrake
    environment:
      - VNC_PASSWORD=casaos # Set the VNC password to 'casaos'
    volumes:
      - ${APP_DATA_DIR}/config:/config:rw
      - ${APP_DATA_DIR}/storage:/storage:ro
      - ${APP_DATA_DIR}/watch:/watch:rw
      - ${APP_DATA_DIR}/output:/output:rw
