version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-raneto_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/raneto:0.18.1@sha256:72464f21361a3a10ac3aaba97bbd60d3ca63e06ee7209fe4a1d40c62c4705c03
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
