version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-raneto_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/raneto:0.18.1@sha256:67ad914a21192ddf9c3e0cce5fb0a5d65c272f00bf04ed2f59e73cb060b64767
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
