version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-msedge_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/msedge:153.0.4234@sha256:e581a986c663d99e9088623d6b1cc677d992cb544b2057083e5e8a746d06c535
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
