version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-msedge_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/msedge:154.0.4258@sha256:74cbcae6d5fea76a2f3c4b105908b8b87cb1b6581fac1970306a5997f33b5120
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
