version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-intellij-idea_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/intellij-idea:42026.2.3@sha256:fd989215cf489a15237096a100df8eeeb7e3b0224c398ac76346bb35b0908da2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
