version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-intellij-idea_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/intellij-idea:42026.2.3@sha256:c8e124dec890657d5010cf07a18e8790a9e1ded61d52c45fc3418cd3a3a76d0e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
