version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dashdot_app_1
      APP_PORT: "3001"
  app:
    image: mauricenino/dashdot:6.3.4@sha256:434a54d2937411a06b09c50e55709cc7d3b092c0fe173a9e5c986f9b5a33c7c6
    volumes:
      - ${APP_DATA_DIR}/data:/mnt/host
    privileged: true
