version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cantinarr_app_1
      APP_PORT: "8585"
  app:
    image: ghcr.io/windoze95/cantinarr:1.0.0@sha256:4d061d80aa66f691b2071b43dafd93b604607effa3138862078a341f973e55d4
    restart: unless-stopped
    environment:
      CANTINARR_PUSH_GATEWAY_URL: https://push.cantinarr.com
      CANTINARR_ARR_CALLBACK_URL: ""
    volumes:
      - ${APP_DATA_DIR}/config:/config
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8585/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - big_bear_cantinarr_network
      - default
networks:
  big_bear_cantinarr_network:
    driver: bridge
