version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-yq_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/yq:4.1.2@sha256:95d4d0f9fc7b0699f74087e7fc6e62eb11c0335447a061cf7425d09c4d32bdfc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
