# Configuration for big-bear-mind setup
version: "3.7"
# Service definitions for the big-bear-mind application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mind_app_1
      APP_PORT: "8080"
  app:
    image: "mrcas/mind:v1.4.1@sha256:152f824d093f2e8772af0d209afc710b9e79edf3e6286d7c3eccb0509dafffd4"
    environment:
      - TZ=UTC
    volumes:
      - ${APP_DATA_DIR}/db:/app/db
