version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kometa_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/kometa:2.5.1@sha256:2e269f44e0e624aae9d80daed7bd5cd2d40e0eb1402f69ce1daa38a65ae5712b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
