version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kometa_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/kometa:2.5.1@sha256:ba1401d2a6a439d76baa2bfa83f8e12e99aef7c4949f386139e3a9b751a5a012
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      KOMETA_CONFIG: ''
      KOMETA_TIMES: ''
      KOMETA_RUN: ''
      KOMETA_TESTS: ''
      KOMETA_NO_MISSING: ''
    volumes:
      - type: bind
        source: /DATA/AppData/kometa/config
        target: /config
