version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kimai_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/kimai:2.68.0@sha256:cd6aa5e2b69743e4b564c446731dbd521c55598527771e36212860cad48854e6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_SECRET: ''
      DATABASE_URL: ''
      TRUSTED_HOSTS: ''
      TRUSTED_PROXIES: ''
    volumes:
      - type: bind
        source: /DATA/AppData/kimai/config
        target: /config
