# Configuration for it-tools setup
# Name of the big-bear-it-tools application
version: "3.7"
# Service definitions for the big-bear-it-tools application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-it-tools_app_1
      APP_PORT: "80"
  # Service name: app
  # The `app` service definition
  app:
    # Image to be used for the container
    image: corentinth/it-tools:2023.11.2-7d94e11@sha256:30b032f2175e9c4dc5c795cfa44354ce7fe76d9768caee0f24a9a7371948ac0d
    # Container restart policy
    restart: unless-stopped
