version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ubooquity_app_1
      APP_PORT: ' 2202'
  app:
    image: linuxserver/ubooquity:3.1.0@sha256:48bcdfdca211fb39831565b1bcab4b7fb17e2f6f05e242dfd42518b314b6823e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      MAXMEM: ''
    volumes:
      - type: bind
        source: /DATA/AppData/ubooquity/config
        target: /config
      - type: bind
        source: /DATA/AppData/ubooquity/books
        target: /books
      - type: bind
        source: /DATA/AppData/ubooquity/comics
        target: /comics
      - type: bind
        source: /DATA/AppData/ubooquity/files
        target: /files
