# Configuration for excalidraw setup
# Application Name
version: "3.7"
# Services used in the application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-excalidraw_app_1
      APP_PORT: "80"
  # The `app` service for the excalidraw application
  app:
    # Docker image to be used
    image: excalidraw/excalidraw:latest@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
    # Restart policy for the service
    restart: unless-stopped
