version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ddclient_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/ddclient:4.0.0@sha256:025d446b276cf63be3c57c8cf54b6206319d1e5f2bbd7acd4def98bba7a32ee4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/ddclient/config
        target: /config
