version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ddclient_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/ddclient:4.0.0@sha256:974d9aab3f1eb9944e88f4f461b5b4372a455132c7955a4977dff67a91a914fb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/ddclient/config
        target: /config
