version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-flycast_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/flycast:2.7.20260927@sha256:a433230c52bd6c0f6f7102aaf05355b01c745aca0f167b3bd80338c290c603e8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
