version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-flycast_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/flycast:2.7.20261004@sha256:e5d9e7b56f1d2ada07ad7e61405bd86c77e54fd908882c62f4a07b9f27ce5628
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/flycast/config
        target: /config
