version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-foldingathome_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/foldingathome:8.5.6@sha256:f24390034073903dbd7ec724eaef27abe464cd729164338701fe3a31927d2dbc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/foldingathome/config
        target: /config
