version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-sealskin_app_1
      APP_PORT: ' 8443'
  app:
    image: linuxserver/sealskin:0.3.2@sha256:8666f0ae5466f94d9d1376bf5ecda0454155c69dda906c5ba844262d069b9394
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
