version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-sealskin_app_1
      APP_PORT: ' 8443'
  app:
    image: linuxserver/sealskin:0.3.2@sha256:25d6fae59c5dda6e2640aba444cad515876c2ba919ad0be7ba94ddf3282ef914
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
