version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-orcaslicer_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/orcaslicer:2.4.2@sha256:14f79f464648f80cdbfb392746b1dcc782d5d80ac40ee4557ab87426012568bd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
