version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-orcaslicer_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/orcaslicer:2.4.2@sha256:209754c74694f6b99cc40cbf313447ba6464a6bdfae722903b25049ce38c6f64
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
