version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-orcaslicer_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/orcaslicer:2.4.2@sha256:b6b97945debcfb9c63dcb9b40a772c46ebedf5c3b15594d2369e9d2b317b8ac9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
