version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dosbox-staging_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/dosbox-staging:0.83.0@sha256:49d643baf92fae352a6f12d3ec148b647cde34fe3e6f6293b5ff97d23790a3e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
