version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dosbox-staging_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/dosbox-staging:0.83.0@sha256:8b1001b35ddf7bcd7b610cdfddcd0e01d8c705fb13e7e69819e83482488ba83a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
