version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ppsspp_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/ppsspp:1.20.4@sha256:947556c22803d2adc12988d3b9eb414dd10a948c45a95966138ca0f937071c55
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/ppsspp/config
        target: /config
