version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ppsspp_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/ppsspp:1.20.4@sha256:c2af8aae650c6da76aa25a4833c0108c6e689d7540ac34de3d3dc1678fb0b818
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/ppsspp/config
        target: /config
