version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-digikam_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/digikam:9.1.0@sha256:60d52929d85e5f251eefce7eba161449a773ea35750ef3e1b5dc4b77e092257d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
