version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-digikam_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/digikam:9.1.0@sha256:b04203ab374fd32d2d44a017c8ef4d01d7ea834b1e4905d8c225440b00bf38ec
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/digikam/config
        target: /config
