version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-winegui_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/winegui:4.5.0@sha256:4307fa122059e94d3f37841b9406cfcf3c76029656411ce93487a3c0e6540360
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/winegui/config
        target: /config
