version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-winegui_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/winegui:4.5.1@sha256:41a12b6613072df63bae0d05331386a84c8a347095f4b99b4f20a9bb72b8517f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/winegui/config
        target: /config
