version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-krita_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/krita:5.3.4@sha256:834c12be2944134c040d4c781cdb3135b1f761ebe6450a7c97c4780534ec10a6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/krita/config
        target: /config
