version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-krita_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/krita:5.3.4@sha256:3a36ff6d2571856cf893f99add3237ec91920401d6066bc44fed5ecad44eb3b5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/krita/config
        target: /config
