version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-krita_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/krita:5.3.4@sha256:965181ce18e3c9c1ace8fdd88c56cf1c381809ebc14a934b34d191ed09d123cd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/krita/config
        target: /config
