version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-limnoria_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/limnoria:2026.5.8@sha256:4b6eae67efc3799d5467268fe86cf3964bc7175f2bb5bafffd8734564cd45565
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
