version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-limnoria_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/limnoria:2026.5.8@sha256:ccbc27f692643d1c79a362262c2ed0c47d870e2a7cd206028b83e19f4c2ca050
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
