version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-darktable_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/darktable:25.6.1@sha256:197c931960bcc8786bc0523ae749654927d89e56e43a6b09cfbf6b3fb3c9bfcb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/darktable/config
        target: /config
