# Configuration for big-bear-onlyoffice setup
version: "3.7"
# Service definitions for the big-bear-onlyoffice application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-onlyoffice_app_1
      APP_PORT: "80"
  app:
    image: onlyoffice/documentserver:9.1.0@sha256:34b92f4a67bfd939bd6b75893e8217556e3b977f81e49472f7e28737b741ba1d
    volumes:
      - ${APP_DATA_DIR}/onlyoffice/logs:/var/log/onlyoffice
      - ${APP_DATA_DIR}/onlyoffice/data:/var/www/onlyoffice/Data
      - ${APP_DATA_DIR}/onlyoffice/lib:/var/lib/onlyoffice
      - ${APP_DATA_DIR}/onlyoffice/rabbitmq:/var/lib/rabbitmq
      - ${APP_DATA_DIR}/onlyoffice/redis:/var/lib/redis
      - ${APP_DATA_DIR}/onlyoffice/db:/var/lib/postgresql
