version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mysql-workbench_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mysql-workbench:8.0.47@sha256:af86f67fcbf7d1e0da9610fb2bf05eda77228ca4995df58976b6f35e42ebd1ac
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mysql-workbench/config
        target: /config
