version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gitqlient_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/gitqlient:1.6.3@sha256:861b55c6e86c056b5543eeb2a88845f7b29b8b5386fa5d6bb9ca73eba21332b5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
