version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gitqlient_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/gitqlient:1.6.3@sha256:1e4a60dae4ef0b6f20f083939c8a5f367a942bc74388126b09d0c27564486d49
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
