version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blender_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blender:5.2.2@sha256:9216c77ab2bf38a758390f802c5777554df605c53456dbcad828509a27a8f28b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
