version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blender_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blender:5.2.2@sha256:8b1377cca1a53009e5e2ad4bc313c21edee6abc89cf0333ef3f06b35a661be11
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
