version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-blender_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/blender:5.2.2@sha256:d66c5758fb64316bcc88a3e779b2d544df5c1d8c320f8003444994906657f230
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
