version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-citron_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/citron:2026.02.1@sha256:6d955bd6dce826c40f3ffdb793c4711826179cf411c2f72c4c27358413195ddb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /srv/lsio/citron/config
        target: /config
