version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-xbackbone_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/xbackbone:3.8.2@sha256:265465d3fe217d8c34bc61ababedaa1127c325032618641cf09827ffeb3436bb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/xbackbone/config
        target: /config
