version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-grocy_app_1
      APP_PORT: ' 9283'
  app:
    image: linuxserver/grocy:4.7.1@sha256:c0d0d9d22d3a54fe3f779a743baa2d7bab96b73fad5597ff1a631e2be4b863c8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
