version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-grocy_app_1
      APP_PORT: ' 9283'
  app:
    image: linuxserver/grocy:4.7.1@sha256:71226f43e18b15836833075c15c9d5d51d81a2a4fc38d56bb1dc05f34970cc80
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
