version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-signal_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/signal:8.28.0@sha256:1552d343e845d1246728a5894f53e0c42804adedcd1a1a36af7f5aff40cf8d8b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
