version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-signal_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/signal:8.29.0@sha256:3eb5e94b6311a74e90b627008782b6c14cefb9167aab5f0709ff3257840e8919
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
