version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-signal_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/signal:8.27.0@sha256:86d2bd83079eb0aa6337b4d86e602c912c70cb5d7c942cc99ce033cc9d80f336
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
