version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-scummvm_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/scummvm:2026.3.0@sha256:bc35e660a1c1f8a7daec895b75f71135cbc4ade6812f7ed74efac82c3308aaf4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/scummvm/config
        target: /config
