version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-scummvm_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/scummvm:2026.3.0@sha256:418ff00e4f4a331117783978e906b852c6df6bc458d5b5c919c31bad4f0a0fdc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/scummvm/config
        target: /config
