version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pcsx2_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pcsx2:2.8.2@sha256:e4744b8392782d57841b40ad502e3420e7938937cb5fb24e37d6bcf48f6a75f1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
