version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pcsx2_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pcsx2:2.8.2@sha256:2dd0400fe54b9ccaaf23d9c2b5bced2eb32c28856f7932b7808036ae49f9a489
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
