version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pcsx2_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pcsx2:2.8.2@sha256:cf33a35769e299772ec213b595c3113cc10416ad67da10ef9f2275c32a3bd83d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
