version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-retroarch_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/retroarch:1.22.2@sha256:f26b343bfacbb5d6d7ecac9221d69eeb5b9451476b0280fc834b18e13e04a696
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
