version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-retroarch_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/retroarch:1.22.2@sha256:855fea1198e3474243e31455c1b42c6a18f354ae4cd275e26063bfcf0cfa1089
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
