version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-retroarch_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/retroarch:1.22.2@sha256:d5b49482a1ba902c3448efc7c6961c574c10e37d1cdfc5273d1230b98dd1562c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
