version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscodium_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vscodium:1.135.06055@sha256:6d299002029dc6fa2aa3cbc5ee0fcd295fe17d2d805cf1e6ede70d2eaeef4798
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium/config
        target: /config
