version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-vscodium_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/vscodium:1.135.06055@sha256:53c93c2387fd2732bed7799ecb204ff2c50217e2912bc48af2c2202419f8e77e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium/config
        target: /config
