version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pelorus_app_1
      APP_PORT: ' 3001'
  app:
    image: linuxserver/pelorus:0.2.3@sha256:1237887b90c7f26ca22b4923a223b7342781ca242a249f048be4fd6fa9451616
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/pelorus/config
        target: /config
