version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dolphin_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/dolphin:version-2606a@sha256:2934f9f01b98669242408c97cfd927ccf308cab108c380f5d4b8dfded5eb5055
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/dolphin/config
        target: /config
