version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-calligra_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/calligra:3.2.1@sha256:7d3f17b566db8ce2fcaf163da9e7df40379668199417f13be904f1ed3fb3dc49
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/calligra/config
        target: /config
