version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-thelounge_app_1
      APP_PORT: ' 9000'
  app:
    image: linuxserver/thelounge:4.5.2@sha256:d8f850ca744bb62319442413c6db93e752a88fc2cb8829f260bc68c9bfce3719
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
