version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-thelounge_app_1
      APP_PORT: ' 9000'
  app:
    image: linuxserver/thelounge:4.5.2@sha256:8793004304efb7744792c55911fc069495ecbc04c46e6054f06c12e7a44074e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/thelounge/config
        target: /config
