version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-python_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/python:3.14.8@sha256:f4ed298459c1d851c245f7cbfc97fdd7ea675d1ea0e11c922f83df29208be365
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/python/config
        target: /config
