version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-telegram_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/telegram:7.2.9@sha256:26ae3c38bcc68d55e493f614deee30b015d2431fd075511ff9cd758c9fa885cd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/telegram/config
        target: /config
