version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-telegram_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/telegram:7.2.8@sha256:84db4e8137d8fcfd07eb92869f307810e1531284499e68c6daca238df4ef49aa
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/telegram/config
        target: /config
