version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-zen_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/zen:1.22.3@sha256:6e66d5e929a2f2b1d387eb4897489e600364e59fefb137a3c5fa13382b2afbcb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/zen/config
        target: /config
