version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-zen_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/zen:1.22.2@sha256:4f8572c3cff3591fe622d2ba69f319e493af6301760c1c1208bc4232d7e01da0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/zen/config
        target: /config
