version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ldap-auth_app_1
      APP_PORT: ' 8888'
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:8939d638970d72a10979e7b1635715fc0ee8ed8cc8ed50b2e0d1c613208f7756
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
