version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ldap-auth_app_1
      APP_PORT: ' 8888'
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:516f35dccd01e8f03d4600f6e1102e3dc20666765336ce08a1b34afd1bf1ea5f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
