version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ldap-auth_app_1
      APP_PORT: ' 8888'
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:4f404fd3b0236e4a3c47a137a6f34d74094cde51471bce66d921f50289b6bf46
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
