version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-babybuddy_app_1
      APP_PORT: ' 8000'
  app:
    image: linuxserver/babybuddy:2.11.0@sha256:d03f380d9bc4a0139015744dd0c402818aed83dbedf5d36a01754e5e600f7f77
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CSRF_TRUSTED_ORIGINS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/babybuddy/config
        target: /config
