version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-babybuddy_app_1
      APP_PORT: ' 8000'
  app:
    image: linuxserver/babybuddy:2.11.0@sha256:b19394db47554ab385e5513dcb4aed253f551a19ac89576a9df191ed59b683de
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CSRF_TRUSTED_ORIGINS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/babybuddy/config
        target: /config
