version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webcord_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webcord:4.14.0@sha256:33f4850371fdc2a01bee9afa7ef2399d8f4c6acbab131a1ccc506fa5eea2d115
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
