version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-webcord_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/webcord:4.14.0@sha256:e27efc7c064dc3dcd4116553bcf6b420c32e7c23573c0e056a2e3ffbe50dfe9f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/webcord/config
        target: /config
