version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-grav_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/grav:2.2.3@sha256:4653d99382683c825afd972dc82f5fd7e1fcb97f1e9d2fdba9ccd2e3a49ef498
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
