version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-helium_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/helium:0.18.1@sha256:4b6dc7b09c6ed8737993f98af689733709ed9fae9e9df5a1b99a686f443eddeb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
