version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-helium_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/helium:0.18.3@sha256:342fbaa7048b733b94bf94b4572d7c3b746c16bc3073e0403a80c77f1429f3c4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
