version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-emby_app_1
      APP_PORT: ' 8096'
  app:
    image: linuxserver/emby:4.10.1@sha256:435fcb7724d3d3ce15a5667075f37edee713fddff4b2854d49bd23a3a46e325d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/emby/config
        target: /config
      - type: bind
        source: /DATA/AppData/emby/data/tvshows
        target: /data/tvshows
      - type: bind
        source: /DATA/AppData/emby/data/movies
        target: /data/movies
      - type: bind
        source: /opt/vc/lib
        target: /opt/vc/lib
