version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mame_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mame:version-0.289dfsg1-0@sha256:0968ba5bd934527a550d0b76cdaaff5bcf1cda16c6ac2850b7f5e68a4b7868d9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
      - type: bind
        source: /DATA/AppData/mame/mame:ro
        target: /mame:ro
