version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mame_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mame:version-0.289dfsg1-0@sha256:045b02470ab2893f366a638478c7944845aabaf29c2dc346394ff3e0485fd4ce
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
      - type: bind
        source: /DATA/AppData/mame/mame:ro
        target: /mame:ro
