version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-remmina_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/remmina:1.4.43@sha256:99a10c613e87f8f31acb1f25565b4c7c8d96b8fbe2c6528897b03d179a8918a6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
