version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-remmina_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/remmina:1.4.43@sha256:a3a1bcd96d73d634d19b80cf1d10422faf9ad5875edb3dcd01d296151d0ed08a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
