version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-remmina_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/remmina:1.4.43@sha256:fa8e87a89b127e8619d091d0a0cdb4fbcba2d706a95fd68403544e97e9631f8c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
