version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-freshrss_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/freshrss:1.30.0@sha256:50f295fe361b2ef467a65232ab488ef161f8a0d6815d28b918c29fcb4a9c9690
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/freshrss/config
        target: /config
