version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-znc_app_1
      APP_PORT: ' 6501'
  app:
    image: linuxserver/znc:1.10.3@sha256:d2bceb0d55c84bb053039724787297b9a8ba4f532182d27eabd47d6e88a5a268
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/znc/config
        target: /config
