version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-znc_app_1
      APP_PORT: ' 6501'
  app:
    image: linuxserver/znc:1.10.3@sha256:b144ed358744eebe779fcca8e4a646ddd8389116cd185849cb2af183d0acb7cb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/znc/config
        target: /config
