version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-piper_app_1
      APP_PORT: ' 10200'
  app:
    image: linuxserver/piper:2.5.2@sha256:82ea64e64668fdde85073f40719d0a9e13ff0ecfb7b89202f661b32d46c1a644
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PIPER_VOICE: ''
      LOCAL_ONLY: ''
      PIPER_LENGTH: ''
      PIPER_NOISE: ''
      PIPER_NOISEW: ''
      PIPER_SPEAKER: ''
      NO_STREAMING: ''
    volumes:
      - type: bind
        source: /DATA/AppData/piper/config
        target: /config
