version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kicad_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/kicad:10.0.3@sha256:27683df5f08133af07588900e1bd8440a9cc3c7e77a5bcfc6bab652f9b185665
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
