version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kicad_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/kicad:10.0.3@sha256:f75208310b82535435aba788a6443fb3ffd3f34ef68eae0b76a55ec2a18160f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
