version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-kicad_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/kicad:10.0.3@sha256:c0da5a64426bbee5d0e95d325959518b7851f7a86ed89c35bc831fb7cc6996ae
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
