# Configuration for big-bear-codex-docs setup
version: "3.7"
# Service definitions for the big-bear-codex-docs application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-codex-docs_app_1
      APP_PORT: "3000"
  app:
    image: ghcr.io/codex-team/codex.docs:v2.2@sha256:c25f47c7f5af84206cef1fcedb2debcd25ba9ce1d4c6e5a33a0f273faff5a41f
    volumes:
      - ${APP_DATA_DIR}/uploads:/usr/src/app/uploads
      - ${APP_DATA_DIR}/db:/usr/src/app/db
      - ${APP_DATA_DIR}/codex-docs-config.local.yaml:/usr/src/app/docs-config.yaml
