version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gitea_big-bear-gitea_1
      APP_PORT: "3000"
  big-bear-gitea:
    image: gitea/gitea:1.26.4
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__SSH_PORT=2222
      # - GITEA__server__DOMAIN=git.example.com
      # - GITEA__server__ROOT_URL=https://git.example.com/
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=3", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
