# Configuration for nexterm setup
# Name of the big-bear-nexterm application
version: "3.7"
# Service definitions for the big-bear-nexterm application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-nexterm_big-bear-nexterm_1
      APP_PORT: "6989"
  # Service name: big-bear-nexterm
  # The `big-bear-nexterm` service definition
  big-bear-nexterm:
    # Image to be used for the container
    image: nexterm/aio:1.2.2-BETA@sha256:def6f6a50b48c842d3fbe796ff8e7ce6b8fa54e2d92116a62742859c64f47d7e
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the big-bear-nexterm container
    environment:
      # REQUIRED: Replace with a strong random key before deploying
      # Generate with: openssl rand -hex 32
      - ENCRYPTION_KEY=
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local nexterm_data directory to /app/data inside the container
      - ${APP_DATA_DIR}/data:/app/data
