# Configuration for ejbca-ce setup
# Name of the big-bear-ejbca-ce application
version: "3.7"
# Service definitions for the big-bear-ejbca-ce application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ejbca-ce_big-bear-ejbca-ce_1
      APP_PORT: "8080"
  # Service name: app
  # The `app` service definition
  big-bear-ejbca-ce:
    # Image to be used for the container
    image: keyfactor/ejbca-ce:9.3.7@sha256:183b86af44b9b13e7cc8912c868f635aeb8dba6bf056ccbd4683b17626964d0a
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local ejbca-ce/persistent directory to /mnt/persistent inside the container
      - ${APP_DATA_DIR}/persistent:/mnt/persistent
    # Environment variables
    environment:
      - TLS_SETUP_ENABLED=simple
