version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-readme-sync_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/readme-sync:84f2d0c3-ls27@sha256:195a6acb0288d92d0c485d99099b93c5f88c0753c560b169ad0e9c758ad48d5f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/readme-sync/config
        target: /config
