version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-tautulli_app_1
      APP_PORT: ' 8181'
  app:
    image: linuxserver/tautulli:2.18.2@sha256:d3c53deb09f6b8fffd1476c7154da538394193955d1e909f3b126068102fb7cf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
