version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-tautulli_app_1
      APP_PORT: ' 8181'
  app:
    image: linuxserver/tautulli:2.18.2@sha256:bfcd2f3f6f89d2171d161ac1780723d1633f8de3c4c993d0dc52aa9edb729e16
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/tautulli/config
        target: /config
