version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-calibre_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/calibre:9.14.0@sha256:63631e9a99f6cbf532759b096d9b51dde8659deb7950ee7d2ee17af0d025c07e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CUSTOM_USER: $CUSTOM_USER
      PASSWORD: $PASSWORD
      CLI_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
