version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-calibre_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/calibre:9.15.0@sha256:59e4b0e036e62f228f8bcfae1ade42f47047719885fe454ddbad38e4597b987b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CUSTOM_USER: $CUSTOM_USER
      PASSWORD: $PASSWORD
      CLI_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
