version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-calibre_app_1
      APP_PORT: ' 8080'
  app:
    image: linuxserver/calibre:9.15.0@sha256:8c7b77ada7133cbac1519791035ac7e305e37adae5cd06038270a90f99f4b4d6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CUSTOM_USER: $CUSTOM_USER
      PASSWORD: $PASSWORD
      CLI_ARGS: ''
    volumes:
      - type: bind
        source: /DATA/AppData/calibre/config
        target: /config
