version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-socket-proxy_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/socket-proxy:3.4.6@sha256:362cadf55b3c7920189347d0f4d60b389e2f80e929581bf10793f2371aab41e5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/socket-proxy/config
        target: /config
