version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-socket-proxy_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/socket-proxy:3.4.6@sha256:0357c479cc98e863917d1cd8b10e83d35a50ca46a0788f5a192bf792c3b7100d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/socket-proxy/config
        target: /config
