version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gzdoom_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/gzdoom:4.14.2@sha256:46e43bf526c458995e4d0d95232415ca8426a3c6737ebc4f10517448cef92142
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/gzdoom/config
        target: /config
