version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gzdoom_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/gzdoom:4.14.2@sha256:c19b50ceabef5835463f8a6ed8d8af4cab0a9e1530d335f795a478d0fc8c9a8c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/gzdoom/config
        target: /config
