version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gzdoom_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/gzdoom:4.14.2@sha256:8478fecca91fbb34a975b4822fb5d391a354873e118a9cb6d99ed0a85ea82023
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/gzdoom/config
        target: /config
