version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pairdrop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pairdrop:1.11.2@sha256:c9fdb5defc4c155bdbd852c6e918064750cdace6ed768e6c61ebbb39d1f80a9f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/pairdrop/config
        target: /config
