version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-pairdrop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/pairdrop:1.11.2@sha256:15b6792fcd486d8ebd1853dbfb0419188ca92035da2f29f75eb18b5390fa25d1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    volumes:
      - type: bind
        source: /DATA/AppData/pairdrop/config
        target: /config
