version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-weixin_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/weixin:version-f1376de7@sha256:200f4b7ed2bb29c6d366e804b8cbea5f7030d7a20f38e11cfeb03e23a6ad79d5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/weixin/config
        target: /config
