version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-diskover_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/diskover:2.3.5@sha256:55e73fd48d91d5594aee57d157e2276fb51917968b06b15a2c9917bb4ed1a01b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ES_HOST: ''
      ES_PORT: ''
    volumes:
      - type: bind
        source: /DATA/AppData/diskover/config
        target: /config
      - type: bind
        source: /DATA/AppData/diskover/data
        target: /data
