version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-librespeed_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/librespeed:6.3.0@sha256:6fb1550f7eb948db17559f14a6837112f580de734f3684ac30bd819443826050
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      CUSTOM_RESULTS: ''
      DB_TYPE: ''
      DB_NAME: ''
      DB_HOSTNAME: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_PORT: ''
      IPINFO_APIKEY: ''
    volumes:
      - type: bind
        source: /DATA/AppData/librespeed/config
        target: /config
