version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-github-desktop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/github-desktop:3.4.13@sha256:a663ba5d99d5c6c2b1f55ba9a5e8a198bc1a957bd910922c85e15aa29645ab0e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
