version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-github-desktop_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/github-desktop:3.4.13@sha256:2af67286e1c584956103af417d9593272f130de8bc6aa4e218efc0c4912bd86b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/github-desktop/config
        target: /config
