version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mstream_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mstream:6.29.0@sha256:fa93d0d7ad01756cc83d7d49252d78517d20871e18d33e171bffd30e865d0156
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mstream/config
        target: /config
      - type: bind
        source: /DATA/AppData/mstream/music
        target: /music
