version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mstream_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/mstream:6.30.0@sha256:896225514e635e6c8084ff6715f3a35f1c74b17d70cb5abbee00c47ece477ccb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/mstream/config
        target: /config
      - type: bind
        source: /DATA/AppData/mstream/music
        target: /music
