# Name of the service
version: "3.7"
# Service configurations
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-mumble-server_app_1
      APP_PORT: "64738"
  # Main application service
  app:
    # Docker image to use
    image: mumblevoip/mumble-server:v1.4.230-6@sha256:42ea734f0a8962cde8c3cd5f0dc5536c9caf6131064093b9ba76ed133b104fc4
    # Hostname for the container
    hostname: mumble-server
    # Restart policy
    restart: on-failure
