version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-filezilla_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/filezilla:3.69.6@sha256:c74d8e56d7a48d7e643e06f4f8119790df0eacbb0340268323704d349c94231f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
