version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-filezilla_app_1
      APP_PORT: ' 3000'
  app:
    image: linuxserver/filezilla:3.69.6@sha256:e9aee91a1a9905ad7299022a34c99ce17244ff5ec5c8950e5efaccad03b82ea3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
