version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dokuwiki_app_1
      APP_PORT: ' 80'
  app:
    image: linuxserver/dokuwiki:version-2026-07-14c@sha256:2a94a05587e8badf13a5500fe2bb2cfd0c1f74e9b2e952b96d304dc99aab126f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/dokuwiki/config
        target: /config
